### ISSUE TITLE
Is there a way to set level to "ignore" for all rules?

### ISSUE THREAD

**Issue by salbertson** [zmbush/coffeelint-ruby#24]
I'd like to provide an empty config, or a config with a couple options in it, without other rules being enabled by default. Is there any way to disable all rules?

**Comment by zmbush** [comment]
Not that I'm aware of. This would probably be better asked on the main coffeelint repo: https://github.com/clutchski/coffeelint

**Comment by zmbush** [comment]
Since this issue was opened over 9 months ago, I'm going to assume that it was resolved.
