### ISSUE TITLE
v1.12 release?

### ISSUE THREAD

**Issue by crearc** [zmbush/coffeelint-ruby#42]
Upgrade to latest version por favor?

**Comment by zmbush** [comment]
Feel free to make a PR with the change. The process is pretty simple: https://github.com/zmbush/coffeelint-ruby/commit/cc4ae5dfc1411565bbec3d16b7dd778ec108b952. I'll be happy to release an updated gem after that.

**Comment by crearc** [comment]
@zmbush can you review the PR?

**Comment by zmbush** [comment]
I will try to get to this tonight. Sorry for the delay.

**Comment by crearc** [comment]
So they just released 1.13 and said that 1.12 is buggy. Will have to do
this again..

**Comment by zmbush** [comment]
I have upgraded to 1.14.0.
