### ISSUE TITLE
bin/coffeelint.rb app.coffee doesn't exit with non-zero status when offenses are found

### ISSUE THREAD

**Issue by maxjacobson** [zmbush/coffeelint-ruby#47]
Hello! And thanks for this lovely gem.

I recently switched to the binstub interface for running coffeelint and discovered that some lints were sneaking thru our continuous integration process. It seems that this interface doesn't use an exit code to indicate whether there were any lints present.

**Comment by zmbush** [comment]
Looks good to me.
